export const NERDC_SYLLABUS: Record<string, string[]> = {
  english: [
    "Comprehension",
    "Summary Writing",
    "Essay Writing",
    "Lexis and Structure (Grammar)",
    "Oral English (Stress, Intonation, Phonetics)",
    "Cloze Test",
    "Vocabulary Development",
    "Registers and Idioms",
  ],

  mathematics: [
    "Number and Numeration",
    "Algebraic Processes",
    "Equations and Inequalities",
    "Quadratic Equations",
    "Variation",
    "Geometry",
    "Mensuration",
    "Trigonometry",
    "Statistics",
    "Probability",
    "Sets",
    "Coordinate Geometry",
  ],

  biology: [
    "Characteristics of Living Things",
    "Cell Biology",
    "Nutrition",
    "Transport Systems",
    "Respiration",
    "Excretion",
    "Reproduction",
    "Coordination and Control",
    "Ecology",
    "Evolution",
    "Genetics",
    "Classification of Living Things",
  ],

  physics: [
    "Measurement and Units",
    "Motion",
    "Force and Motion",
    "Work, Energy and Power",
    "Heat and Temperature",
    "Waves",
    "Light (Optics)",
    "Sound",
    "Electricity",
    "Magnetism",
    "Atomic Physics",
  ],

  chemistry: [
    "Matter and Separation Techniques",
    "Atomic Structure",
    "Periodic Table",
    "Chemical Bonding",
    "States of Matter",
    "Acids, Bases and Salts",
    "Chemical Equilibrium",
    "Electrolysis",
    "Energy Changes",
    "Organic Chemistry",
    "Metals and Non-metals",
    "Environmental Chemistry",
  ],

  economics: [
    "Basic Economic Concepts",
    "Demand and Supply",
    "Theory of Production",
    "Cost and Revenue",
    "Market Structure",
    "National Income",
    "Money and Banking",
    "Inflation",
    "Public Finance",
    "International Trade",
    "Economic Development",
  ],

  government: [
    "Concept of Government",
    "Constitution",
    "Democracy",
    "Arms of Government",
    "Political Ideologies",
    "Electoral System",
    "Political Parties",
    "Pressure Groups",
    "Public Administration",
    "International Organizations",
    "Nigerian Political History",
  ],

  geography: [
    "Map Reading and Interpretation",
    "The Earth and its Structure",
    "Rocks and Landforms",
    "Climate and Weather",
    "Vegetation",
    "Population Geography",
    "Settlement Geography",
    "Economic Activities",
    "Environmental Resources",
    "Regional Geography (Nigeria and Africa)",
  ],

  commerce: [
    "Introduction to Commerce",
    "Production",
    "Trade",
    "Aids to Trade",
    "Business Units",
    "Marketing",
    "Transportation",
    "Warehousing",
    "Insurance",
    "Banking",
    "Foreign Trade",
  ],

  accounting: [
    "Principles of Accounting",
    "Double Entry System",
    "Books of Original Entry",
    "Ledger Accounts",
    "Trial Balance",
    "Final Accounts",
    "Bank Reconciliation",
    "Depreciation",
    "Control Accounts",
    "Partnership Accounts",
    "Company Accounts",
  ],

  crk: [
    "Creation and Fall of Man",
    "Covenant (Abraham and Moses)",
    "Leadership in Israel",
    "Prophets in Israel",
    "Life and Teachings of Jesus Christ",
    "Miracles of Jesus",
    "Parables of Jesus",
    "Early Church",
    "Pauline Epistles",
    "Christian Ethics",
  ],

  irk: [
    "Qur'an and Hadith",
    "Articles of Faith (Iman)",
    "Five Pillars of Islam",
    "Life of Prophet Muhammad (S.A.W)",
    "Hijrah and Early Islam",
    "Islamic Moral Teachings",
    "Shariah Principles",
    "Islamic Worship",
    "Islamic History",
    "Islamic Civilization",
  ],

  civiledu: [
    "Citizenship",
    "Fundamental Human Rights",
    "Democracy and Rule of Law",
    "The Constitution",
    "National Values",
    "Drug Abuse Education",
    "Security Education",
    "Political Apathy",
    "Social Justice",
    "National Unity",
  ],

  englishlit: [
    "Prose",
    "Drama",
    "Poetry",
    "Literary Devices",
    "Themes and Analysis",
    "African Literature",
    "Non-African Literature",
    "Appreciation and Criticism",
  ],

  insurance: [
    "Introduction to Insurance",
    "Principles of Insurance",
    "Types of Insurance",
    "Life Assurance",
    "Marine Insurance",
    "Fire Insurance",
    "Motor Insurance",
    "Insurance Documents",
    "Risk Management",
    "Insurance Institutions",
  ],

  history: [
    "African Traditional Society",
    "Trans-Saharan Trade",
    "European Contact with Africa",
    "Colonial Rule in Africa",
    "Nigerian Pre-Colonial States",
    "Amalgamation of Nigeria",
    "Nationalism",
    "Independence Movements",
    "Post-Independence Nigeria",
    "Military Rule in Nigeria",
    "International Relations",
  ],
};