import type { TopicAnalytics } from "@/types";

export const SUBJECTS: string[] = [
  "english",
  "mathematics",
  "biology",
  "physics",
  "chemistry",
  "economics",
  "government",
  "geography",
  "commerce",
  "accounting",
  "crk",
  "irk",
  "civiledu",
  "englishlit",
  "insurance",
  "history",
];

export const EXAM_EXPLANATION_STYLE: Record<string, string> = {
  wassce: `Write the explanation as a WAEC chief examiner would in a marking scheme:
    - State the concept/law/formula being tested
    - Show full working or reasoning step by step
    - State why the correct answer is arrived at
    - In one sentence, state why the distractors are wrong
    - End with: "Examiner's tip: ..." relevant to WAEC marking`,

  neco: `Write the explanation as a NECO examiner would:
    - Reference the Nigerian national curriculum topic directly
    - Explain the concept in plain, accessible language
    - Walk through the reasoning to the correct answer clearly
    - Note one common mistake candidates make on this type of question
    - End with: "Examiner's tip: ..." relevant to NECO candidates`,

  utme: `Write the explanation as a JAMB examiner would in a UTME review guide:
    - Identify the exact JAMB syllabus point being tested
    - Show the fastest route to the correct answer (speed matters in UTME)
    - Include any elimination strategy or shortcut applicable
    - Warn about the most tempting wrong option and why it's a trap
    - End with: "Examiner's tip: ..." relevant to UTME time pressure`,

  "post-utme": `Write the explanation as a university post-UTME examiner would:
    - State the advanced concept or application being assessed
    - Provide a thorough explanation with reasoning at 100-level depth
    - Show any working, derivation, or logical proof where relevant
    - Distinguish this question's depth from standard UTME treatment
    - End with: "Examiner's tip: ..." relevant to post-UTME screening`,
};

// Fallback for unknown exam types
export const DEFAULT_EXPLANATION_STYLE = `Write the explanation as a professional Nigerian exam examiner:
    - Identify the concept being tested
    - Explain the reasoning to the correct answer step by step
    - Note why the other options are incorrect
    - End with: "Examiner's tip: ..."`;

export const TOPIC_ANALYTICS: TopicAnalytics[] = [
  {
    course_id: "arrays",
    course_name: "Arrays",
    total_questions: 24,
    correct: 20,
    accuracy: 83,
  },
  {
    course_id: "arrays",
    course_name: "Arrays",
    total_questions: 18,
    correct: 16,
    accuracy: 89,
  },
  {
    course_id: "trees",
    course_name: "Trees",
    total_questions: 20,
    correct: 14,
    accuracy: 70,
  },
  {
    course_id: "graphs",
    course_name: "Graphs",
    total_questions: 16,
    correct: 9,
    accuracy: 56,
  },
  {
    course_id: "complexity",
    course_name: "Time Complexity",
    total_questions: 22,
    correct: 15,
    accuracy: 68,
  },
];

export const TESTIMONIALS = [
  {
    name: "Adaeze Okonkwo",
    school: "UNILAG",
    text: "ExamQuest helped me score 287 in UTME. The practice questions are so similar to the real exam!",
    avatar: "AO",
  },
  {
    name: "Tunde Fashola",
    school: "OAU",
    text: "I was failing my Data Structures course. After 3 weeks on ExamQuest, I scored a B+. The explanations are excellent.",
    avatar: "TF",
  },
  {
    name: "Chioma Eze",
    school: "UI",
    text: "The streak feature keeps me consistent. I haven't missed a day of study in 30 days. My grades improved massively.",
    avatar: "CE",
  },
  {
    name: "Emeka Obi",
    school: "UNIBEN",
    text: "Best exam prep platform in Nigeria. The WAEC past questions cover every topic in the syllabus.",
    avatar: "EO",
  },
  {
    name: "Fatima Musa",
    school: "ABU",
    text: "The analytics dashboard shows exactly where I'm weak. I know what to study every time I open the app.",
    avatar: "FM",
  },
];

export const FAQ = [
  {
    q: "Is ExamQuest free to use?",
    a: "Yes! ExamQuest has a free tier with access to past questions and basic analytics. Premium unlocks unlimited practice, AI explanations, and detailed analytics.",
  },
  {
    q: "Which exams does ExamQuest cover?",
    a: "We cover WAEC, NECO, JAMB UTME, Post-UTME, and University-level courses across all major Nigerian universities.",
  },
  {
    q: "How up-to-date are the questions?",
    a: "Our question bank is updated after every exam season with the latest past questions and new likely questions generated by our content team.",
  },
  {
    q: "Can I use ExamQuest offline?",
    a: "Not yet — ExamQuest requires an internet connection. Offline mode is planned for a future update.",
  },
  {
    q: "How is my score calculated?",
    a: "Your score is the percentage of correct answers. In quiz mode, unanswered questions count as incorrect. In study mode, you can retry questions.",
  },
  {
    q: "Which universities are supported for Post-UTME?",
    a: "We currently support 50+ universities including UNILAG, UI, OAU, UNN, ABU, UNIBEN, FUTA, Covenant University, and more. We add new schools every month.",
  },
];
