import type {
  School,
  Course,
  Quiz,
  LeaderboardEntry,
  ScoreOverTime,
  TopicAnalytics,
  UserCourseProgress,
} from "@/types";

export const SCHOOLS: School[] = [
  {
    id: "unilag",
    name: "University of Lagos",
    short_name: "UNILAG",
    type: "university",
    state: "Lagos",
  },
  {
    id: "ui",
    name: "University of Ibadan",
    short_name: "UI",
    type: "university",
    state: "Oyo",
  },
  {
    id: "oau",
    name: "Obafemi Awolowo University",
    short_name: "OAU",
    type: "university",
    state: "Osun",
  },
  {
    id: "unn",
    name: "University of Nigeria, Nsukka",
    short_name: "UNN",
    type: "university",
    state: "Enugu",
  },
  {
    id: "abu",
    name: "Ahmadu Bello University",
    short_name: "ABU",
    type: "university",
    state: "Kaduna",
  },
  {
    id: "covenant",
    name: "Covenant University",
    short_name: "CU",
    type: "university",
    state: "Ogun",
  },
  {
    id: "futa",
    name: "Federal University of Technology, Akure",
    short_name: "FUTA",
    type: "university",
    state: "Ondo",
  },
  {
    id: "uniben",
    name: "University of Benin",
    short_name: "UNIBEN",
    type: "university",
    state: "Edo",
  },
  {
    id: "unilorin",
    name: "University of Ilorin",
    short_name: "UNILORIN",
    type: "university",
    state: "Kwara",
  },
  {
    id: "babcock",
    name: "Babcock University",
    short_name: "Babcock",
    type: "university",
    state: "Ogun",
  },
];

export const COURSES: Course[] = [];

export const MOCK_QUIZ_HISTORY: Quiz[] = [
  {
    id: "qz1",
    user_id: "u1",
    course_id: "csc101",
    course_name: "Data Structures",
    status: "completed",
    mode: "quiz",
    total_questions: 20,
    time_limit_seconds: 1200,
    time_taken_seconds: 1125,
    difficulty: "medium",
    score_percent: 85,
    correct_count: 17,
    incorrect_count: 3,
    skipped_count: 0,
    started_at: "2026-04-29T10:00:00Z",
    completed_at: "2026-04-29T10:18:45Z",
  },
  {
    id: "qz2",
    user_id: "u1",
    course_id: "csc201",
    course_name: "Operating Systems",
    status: "completed",
    mode: "quiz",
    total_questions: 20,
    time_limit_seconds: 1200,
    time_taken_seconds: 930,
    difficulty: "medium",
    score_percent: 72,
    correct_count: 14,
    incorrect_count: 6,
    skipped_count: 0,
    started_at: "2026-04-28T14:00:00Z",
    completed_at: "2026-04-28T14:15:30Z",
  },
  {
    id: "qz3",
    user_id: "u1",
    course_id: "csc301",
    course_name: "Database Systems",
    status: "completed",
    mode: "quiz",
    total_questions: 20,
    time_limit_seconds: 1200,
    time_taken_seconds: 1210,
    difficulty: "hard",
    score_percent: 65,
    correct_count: 13,
    incorrect_count: 7,
    skipped_count: 0,
    started_at: "2026-04-27T16:00:00Z",
    completed_at: "2026-04-27T16:20:10Z",
  },
  {
    id: "qz4",
    user_id: "u1",
    course_id: "csc101",
    course_name: "Data Structures",
    status: "completed",
    mode: "study",
    total_questions: 15,
    difficulty: "easy",
    score_percent: 93,
    correct_count: 14,
    incorrect_count: 1,
    skipped_count: 0,
    started_at: "2026-04-26T09:00:00Z",
    completed_at: "2026-04-26T09:25:00Z",
  },
  {
    id: "qz5",
    user_id: "u1",
    course_id: "alg101",
    course_name: "Algorithms",
    status: "completed",
    mode: "quiz",
    total_questions: 20,
    time_limit_seconds: 1200,
    time_taken_seconds: 1050,
    difficulty: "hard",
    score_percent: 58,
    correct_count: 11,
    incorrect_count: 8,
    skipped_count: 1,
    started_at: "2026-04-25T11:00:00Z",
    completed_at: "2026-04-25T11:17:30Z",
  },
  {
    id: "qz6",
    user_id: "u1",
    course_id: "csc401",
    course_name: "Computer Networks",
    status: "completed",
    mode: "quiz",
    total_questions: 20,
    time_limit_seconds: 1200,
    time_taken_seconds: 800,
    difficulty: "medium",
    score_percent: 78,
    correct_count: 15,
    incorrect_count: 4,
    skipped_count: 1,
    started_at: "2026-04-24T15:00:00Z",
    completed_at: "2026-04-24T15:13:20Z",
  },
];

export const SCORE_OVER_TIME: ScoreOverTime[] = [
  { date: "Apr 20", score: 62 },
  { date: "Apr 21", score: 58 },
  { date: "Apr 22", score: 70 },
  { date: "Apr 23", score: 65 },
  { date: "Apr 24", score: 78 },
  { date: "Apr 25", score: 58 },
  { date: "Apr 26", score: 93 },
  { date: "Apr 27", score: 65 },
  { date: "Apr 28", score: 72 },
  { date: "Apr 29", score: 85 },
];

export const TOPIC_ANALYTICS: TopicAnalytics[] = [
  {
    course_id: "arrays",
    course_name: "Arrays",
    total_questions: 24,
    correct: 20,
    accuracy: 83,
  },
  {
    course_id: "arrays",
    course_name: "Arrays",
    total_questions: 18,
    correct: 16,
    accuracy: 89,
  },
  {
    course_id: "trees",
    course_name: "Trees",
    total_questions: 20,
    correct: 14,
    accuracy: 70,
  },
  {
    course_id: "graphs",
    course_name: "Graphs",
    total_questions: 16,
    correct: 9,
    accuracy: 56,
  },
  {
    course_id: "complexity",
    course_name: "Time Complexity",
    total_questions: 22,
    correct: 15,
    accuracy: 68,
  },
];

export const COURSE_PROGRESS: UserCourseProgress[] = [
  {
    user_id: "u1",
    course_id: "csc101",
    course_name: "Data Structures",
    progress_percent: 72,
    total_quizzes: 12,
    average_score: 78,
    highest_score: 93,
    last_practiced_at: "2026-04-29T10:00:00Z",
  },
  {
    user_id: "u1",
    course_id: "csc201",
    course_name: "Operating Systems",
    progress_percent: 45,
    total_quizzes: 6,
    average_score: 68,
    highest_score: 72,
    last_practiced_at: "2026-04-28T14:00:00Z",
  },
  {
    user_id: "u1",
    course_id: "csc301",
    course_name: "Database Systems",
    progress_percent: 30,
    total_quizzes: 4,
    average_score: 62,
    highest_score: 65,
    last_practiced_at: "2026-04-27T16:00:00Z",
  },
  {
    user_id: "u1",
    course_id: "alg101",
    course_name: "Algorithms",
    progress_percent: 20,
    total_quizzes: 3,
    average_score: 55,
    highest_score: 58,
    last_practiced_at: "2026-04-25T11:00:00Z",
  },
];

export const LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    user_id: "l1",
    full_name: "Chukwuemeka Obi",
    score: 9850,
    quizzes_completed: 48,
    streak: 21,
  },
  {
    rank: 2,
    user_id: "l2",
    full_name: "Amara Nwosu",
    score: 9210,
    quizzes_completed: 42,
    streak: 18,
  },
  {
    rank: 3,
    user_id: "l3",
    full_name: "Tunde Adeleke",
    score: 8790,
    quizzes_completed: 39,
    streak: 14,
  },
  {
    rank: 4,
    user_id: "l4",
    full_name: "Ngozi Eze",
    score: 8340,
    quizzes_completed: 36,
    streak: 12,
  },
  {
    rank: 5,
    user_id: "l5",
    full_name: "Bola Fashola",
    score: 7980,
    quizzes_completed: 33,
    streak: 10,
  },
  {
    rank: 6,
    user_id: "u1",
    full_name: "You",
    score: 7540,
    quizzes_completed: 30,
    streak: 7,
    is_current_user: true,
  },
  {
    rank: 7,
    user_id: "l7",
    full_name: "Kemi Adeyemi",
    score: 7210,
    quizzes_completed: 28,
    streak: 8,
  },
  {
    rank: 8,
    user_id: "l8",
    full_name: "Emeka Okafor",
    score: 6890,
    quizzes_completed: 25,
    streak: 5,
  },
  {
    rank: 9,
    user_id: "l9",
    full_name: "Sola Adebayo",
    score: 6540,
    quizzes_completed: 22,
    streak: 4,
  },
  {
    rank: 10,
    user_id: "l10",
    full_name: "Funmi Olawale",
    score: 6100,
    quizzes_completed: 20,
    streak: 3,
  },
];


export const TESTIMONIALS = [
  {
    name: "Adaeze Okonkwo",
    school: "UNILAG",
    text: "ExamQuest helped me score 287 in UTME. The practice questions are so similar to the real exam!",
    avatar: "AO",
  },
  {
    name: "Tunde Fashola",
    school: "OAU",
    text: "I was failing my Data Structures course. After 3 weeks on ExamQuest, I scored a B+. The explanations are excellent.",
    avatar: "TF",
  },
  {
    name: "Chioma Eze",
    school: "UI",
    text: "The streak feature keeps me consistent. I haven't missed a day of study in 30 days. My grades improved massively.",
    avatar: "CE",
  },
  {
    name: "Emeka Obi",
    school: "UNIBEN",
    text: "Best exam prep platform in Nigeria. The WAEC past questions cover every topic in the syllabus.",
    avatar: "EO",
  },
  {
    name: "Fatima Musa",
    school: "ABU",
    text: "The analytics dashboard shows exactly where I'm weak. I know what to study every time I open the app.",
    avatar: "FM",
  },
];

export const FAQ = [
  {
    q: "Is ExamQuest free to use?",
    a: "Yes! ExamQuest has a free tier with access to past questions and basic analytics. Premium unlocks unlimited practice, AI explanations, and detailed analytics.",
  },
  {
    q: "Which exams does ExamQuest cover?",
    a: "We cover WAEC, NECO, JAMB UTME, Post-UTME, and University-level courses across all major Nigerian universities.",
  },
  {
    q: "How up-to-date are the questions?",
    a: "Our question bank is updated after every exam season with the latest past questions and new likely questions generated by our content team.",
  },
  {
    q: "Can I use ExamQuest offline?",
    a: "Not yet — ExamQuest requires an internet connection. Offline mode is planned for a future update.",
  },
  {
    q: "How is my score calculated?",
    a: "Your score is the percentage of correct answers. In quiz mode, unanswered questions count as incorrect. In study mode, you can retry questions.",
  },
  {
    q: "Which universities are supported for Post-UTME?",
    a: "We currently support 50+ universities including UNILAG, UI, OAU, UNN, ABU, UNIBEN, FUTA, Covenant University, and more. We add new schools every month.",
  },
];
